feat: add error annotation

diff --git a/.github/workflows/pull_request.redirects.yml b/.github/workflows/pull_request.redirects.yml
--- a/.github/workflows/pull_request.redirects.yml
+++ b/.github/workflows/pull_request.redirects.yml
@@ -68,4 +68,6 @@ jobs:
             ```
 
       - name: 🚦 Check for errors
-        run: exit ${{ steps.validate.outputs.exitCode }}
+        run: |
+          echo "::error::Validate stderr${{ steps.validate.outputs.stderr }}"
+          exit ${{ steps.validate.outputs.exitCode }}
